apiVersion: v1
kind: Service
metadata:
  name: symdon-oauth2-proxy
  labels:
    app: oauth2-proxy
spec:
  type: ClusterIP
  selector:
    app: oauth2-proxy
  ports:
    - name: http
      port: 4180
      protocol: TCP
      targetPort: 4180

---
apiVersion: v1
kind: Service
metadata:
  name: symdon-mailhog
  labels:
    app: mailhog
spec:
  type: ClusterIP
  selector:
    app: mailhog
  ports:
    - name: http
      port: 8025
      protocol: TCP
      targetPort: 8025


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  labels:
    app: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
      - name: mailhog
        image: mailhog/mailhog
        ports:
        - containerPort: 1025
        - containerPort: 8025

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  labels:
    app: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/pusher/oauth2_proxy:v4.0.0
        args:
          - "--http-address=0.0.0.0:4180"
          - "--email-domain=gmail.com"
          - "--upstream=http://localhost:8025/"
        ports:
        - containerPort: 4180
        env:
        - name: OAUTH2_PROXY_REDIRECT_URL
          value: "http://127.0.0.1:4180/oauth2/callback"
        - name: OAUTH2_PROXY_COOKIE_HTTPONLY
          value: "false"
        - name: OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER
          value: "false"
        - name: OAUTH2_PROXY_REDIRECT_URL
          value: "http://127.0.0.1/oauth2/callback"
        - name: OAUTH2_PROXY_COOKIE_SECURE
          value: "false"
        envFrom:
        - secretRef:
            name: symdon
