apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: symdon-oauth2-proxy-ing
  labels:
    app.kubernetes.io/name: symdon-oauth2-proxy
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 1000m
    nginx.ingress.kubernetes.io/auth-url: "http://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://$host/oauth2/start?rd=$escaped_request_uri"

spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: solemn-badger-mailhog
          servicePort: 8025

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oauth2-proxy
spec:
  rules:
  - http:
      paths:
      - path: /oauth2
        backend:
          serviceName: sad-sheep-oauth2-proxy
          servicePort: 80
