service:
  port: 4180

extraArgs:
  "upstream": "http://symdon-mailhog.default.svc.cluster.local:8025/"

extraEnv:
  - name: "OAUTH2_PROXY_UPSTREAM"
    value: "http://symdon-mailhog.default.svc.cluster.local:8025"

  - name: "OAUTH2_PROXY_REDIRECT_URL"
    value: "http://127.0.0.1/oauth2/callback"

  - name: "OAUTH2_PROXY_EMAIL_DOMAIN"
    value: "*"

  - name: "OAUTH2_PROXY_COOKIE_HTTPONLY"
    value: "false"

  - name: "OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER"
    value: "false"

  - name: "OAUTH2_PROXY_COOKIE_SECURE"
    value: "false"
